name: API Tests
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Install Bruno CLI
      run: npm install -g @usebruno/cli
    
    - name: Start API server
      run: nohup npm start &
    
    - name: Wait for server to be ready
      run: |
        for i in {1..10}; do
          nc -z localhost 3000 && echo "Server is up!" && exit 0
          sleep 2
        done
        echo "Server did not start in time" && exit 1
    
    - name: Run API Tests
      run: bru run crud-collection.bru --env ci --reporter-html results.html
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: results.html